### PR TITLE
Mix up CI config

### PR DESCRIPTION
**Pull request by Plecra**
Trying out an alternative setup for the CI to see in the code coverage makes any more sense.

I just ripped this straight from bincode's GH workflow. No idea if it'll work >.>

Edit: yea okay, that won't trigger them. I'll see if I can get them to run in my own repo

### CODE REVIEW

**Comment by Plecra** [comment]
Nice! This looks more like I'd expect. Do I need to add something to the workflow to signal that codecov bot you've got?

https://codecov.io/gh/Plecra/dotenv/branch/use-gh-actions

**Comment by ZoeyR** [comment]
Its probably getting triggered because github actions isn't set up on the repo. I'll make a small PR just to add a minimal Rust config, merge that. Then you can rebase and it should get picked up

**Comment by Plecra** [comment]
Feel free to just use this config - It looks to be behaving in my repo https://github.com/Plecra/dotenv/pull/1

**Comment by Plecra** [comment]
Great, I'll close this in favor of #56

**Pull request closed without merging**
